# Lecture Note 1
## Example of Matrix Exponential

In [11]:
import numpy as np
import math
import scipy.linalg as la
import matplotlib.pyplot as plt


A = np.mat('1, 2,1;3,4,10;2,3,1')


def my_matrixExp(A):     # this is not a numerically stable way to compute matrix exponential
    eA = np.eye(len(A))
    for i in range(30):
        eA = eA + la.fractional_matrix_power(A,i+1)/math.factorial(i+1)
    return eA

    
print(la.expm(A))

print(my_matrixExp(A))




[[1173.93288011 1729.72991464 2240.37273809]
 [3970.10265273 5853.97503259 7583.74032356]
 [1729.72991464 2550.22365322 3303.75137937]]
[[1173.2758373813317 1728.5756577508012 2239.0861421672266]
 [3967.6610863665733 5842.765639833368 7571.375962400923]
 [1728.5756577508012 2548.4960429214743 3301.835382910348]]
